permissions:
  contents: read  
  
on:
  push:
    branches: [ "main" ,"test", "stagin"]
  workflow_dispatch:

jobs:
  init:
    name: CI Workflow
    uses: codeparceorg/ci-workflows/.github/workflows/spring-init.yml@container-app
    with:
      java-version: 17
    secrets: inherit
      